### ISSUE TITLE
Model download?

### ISSUE THREAD

**Issue by antithing** [ZtoYtoQ/NCNN-PoseEstimation#1]
Hi, and thanks for making this code available. 
I am unable to download the model from baidu, would it be possible for you to upload it somewhere else, or add it to this repo?

Thank you!

**Comment by ZtoYtoQ** [comment]
Hi, I have added model to this rero😀. 
https://github.com/ZtoYtoQ/NCNN-PoseEstimation/releases

**Comment by antithing** [comment]
Thank you! Works great.
